# Generated by Django 5.1.6 on 2025-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspicious_activity', models.BooleanField(blank=True, null=True)),
                ('security_measures', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('partner_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('category', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'business_partner_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('component_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=255)),
                ('component_description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('reorder_point', models.IntegerField()),
                ('current_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequests',
            fields=[
                ('delivery_request_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('request_type', models.TextField()),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('quantity_requested', models.IntegerField()),
            ],
            options={
                'db_table': 'delivery_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability_status', models.TextField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('labor_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_worked', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.IntegerField()),
            ],
            options={
                'db_table': 'labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrdersDetails',
            fields=[
                ('production_order_detail_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('actual_quantity', models.IntegerField()),
                ('cost_of_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rework_required', models.BooleanField()),
                ('rework_notes', models.TextField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'production_orders_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrdersHeader',
            fields=[
                ('production_order_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('target_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_orders_header',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_level', models.IntegerField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('material_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesPermission',
            fields=[
                ('role_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('access_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('application_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('stored_materials', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
    ]
