# Generated by Django 5.1.6 on 2025-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlanketAgreement',
            fields=[
                ('agreement_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_method', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blanket_agreement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignContacts',
            fields=[
                ('contact_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('response_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaigns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gl_account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('salesrep_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('lead_phonenum', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('opportunity_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('salesrep_id', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_closed_date', models.DateField(blank=True, null=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_lost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opportunities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rework_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_issue_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('order_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('payment_status', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quotation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('signed_docu', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RenewalWarranty',
            fields=[
                ('renewal_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('original_warranty_start', models.DateField(blank=True, null=True)),
                ('original_warranty_end', models.DateField(blank=True, null=True)),
                ('renewal_warranty_start', models.DateField(blank=True, null=True)),
                ('renewal_warranty_end', models.DateField(blank=True, null=True)),
                ('renewal_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'renewal_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesCosting',
            fields=[
                ('sales_costing_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('non_project_costing_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_resources_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_costing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('invoice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_status', models.TextField(blank=True, null=True)),
                ('payment_status', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('shipping_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operational_cost_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_method', models.TextField(blank=True, null=True)),
                ('tracking_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('salesrep_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('total_tax', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                ('statement_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_md_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('demand_level', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statement_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('salesrep_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketConvo',
            fields=[
                ('convo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_convo',
                'managed': False,
            },
        ),
    ]
