# Generated by Django 5.1.6 on 2025-04-11 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_modules', '0002_blanketagreement_campaigncontacts_campaigns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTracking',
            fields=[
                ('attendance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('late_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('undertime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_holiday', models.BooleanField(blank=True, null=True)),
                ('holiday_type', models.CharField(blank=True, max_length=20, null=True)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('is_workday', models.BooleanField()),
                ('is_holiday', models.BooleanField()),
                ('is_special', models.BooleanField()),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_path', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(blank=True, max_length=50, null=True)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('interview_details', models.JSONField(blank=True, null=True)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('contract_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('delivery_note_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rework_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_method', models.TextField(blank=True, null=True)),
                ('tracking_num', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipment_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_archived', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalances',
            fields=[
                ('balance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sick_leave_remaining', models.IntegerField(blank=True, null=True)),
                ('vacation_leave_remaining', models.IntegerField(blank=True, null=True)),
                ('maternity_leave_remaining', models.IntegerField(blank=True, null=True)),
                ('paternity_leave_remaining', models.IntegerField(blank=True, null=True)),
                ('solo_parent_leave_remaining', models.IntegerField(blank=True, null=True)),
                ('unpaid_leave_taken', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_leave_balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('performance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus_payment_month', models.IntegerField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_supervisor', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('salary_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectCostManagement',
            fields=[
                ('project_resources_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget_approval', models.TextField()),
            ],
            options={
                'db_table': 'external_project_cost_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectDetails',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_status', models.TextField()),
            ],
            options={
                'db_table': 'external_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectEquipments',
            fields=[
                ('project_equipment_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_equipment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_equipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectLabor',
            fields=[
                ('project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectRequest',
            fields=[
                ('ext_project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ext_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_project_description', models.TextField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'external_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTaskList',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.TextField()),
                ('task_deadline', models.DateField()),
            ],
            options={
                'db_table': 'external_project_task_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectTracking',
            fields=[
                ('project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_milestone', models.TextField()),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'external_project_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectWarranty',
            fields=[
                ('project_warranty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warranty_coverage_yr', models.IntegerField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
            ],
            options={
                'db_table': 'external_project_warranty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectCostManagement',
            fields=[
                ('intrnl_project_resources_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget_approval', models.TextField()),
            ],
            options={
                'db_table': 'internal_project_cost_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectDetails',
            fields=[
                ('intrnl_project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_project_status', models.TextField()),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectLabor',
            fields=[
                ('intrnl_project_labor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_job_role_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'internal_project_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectRequest',
            fields=[
                ('project_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('target_starting_date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_budget_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_project_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTaskList',
            fields=[
                ('intrnl_task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_task_description', models.TextField(blank=True, null=True)),
                ('intrnl_task_status', models.TextField()),
                ('intrnl_task_deadline', models.DateField()),
            ],
            options={
                'db_table': 'internal_project_task_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalProjectTracking',
            fields=[
                ('intrnl_project_tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intrnl_start_date', models.DateField()),
                ('intrnl_estimated_end_date', models.DateField()),
                ('intrnl_project_issue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_project_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('position_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_days', models.SmallIntegerField(blank=True, null=True)),
                ('finance_approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('finance_approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('posting_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_posting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('leave_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('management_approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notifications_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('module', models.CharField()),
                ('to_user_id', models.CharField()),
                ('message', models.TextField()),
                ('notifications_status', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField(blank=True, null=True)),
                ('pay_period_end', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('holiday_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('thirteenth_month_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sss_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('philhealth_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pagibig_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('late_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('absent_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('undertime_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('position_title', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('typical_duration_days', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('admin_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('demand_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_pricing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('project_equipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMonitoring',
            fields=[
                ('report_monitoring_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('report_type', models.TextField()),
                ('report_title', models.CharField(blank=True, max_length=255, null=True)),
                ('received_from', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_monitoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resignations',
            fields=[
                ('resignation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('clearance_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resignations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'return',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReworkCost',
            fields=[
                ('rework_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_misc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rework_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'rework_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceAllocation',
            fields=[
                ('allocation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workforce_allocation',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Components',
        ),
        migrations.DeleteModel(
            name='DeliveryRequests',
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='RenewalWarranty',
        ),
        migrations.DeleteModel(
            name='SalesCosting',
        ),
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
        migrations.CreateModel(
            name='DepartmentSuperiors',
            fields=[
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='connected_modules.departments')),
                ('hierarchy_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department_superiors',
                'managed': False,
            },
        ),
    ]
