# Generated by Django 5.1.6 on 2025-04-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_modules', '0003_attendancetracking_calendardates_candidates_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('additional_service_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'additional_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalServiceType',
            fields=[
                ('additional_service_type_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_type', models.TextField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('status', models.TextField()),
                ('total_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'additional_service_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfterAnalysisSched',
            fields=[
                ('analysis_sched_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_status', models.TextField()),
            ],
            options={
                'db_table': 'after_analysis_sched',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('delivery_status', models.TextField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalysis',
            fields=[
                ('analysis_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_status', models.TextField()),
                ('analysis_description', models.TextField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'service_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceBilling',
            fields=[
                ('service_billing_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outsource_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operational_cost_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_status', models.TextField()),
                ('date_paid', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('service_call_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('service_ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('call_type', models.TextField()),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('call_status', models.TextField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority_level', models.TextField()),
                ('resolution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('contract_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('statement_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_status', models.TextField()),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('renewal_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('service_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'service_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('service_order_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'service_order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_status', models.TextField()),
                ('request_type', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('service_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.TextField()),
                ('request_status', models.TextField()),
                ('request_description', models.TextField(blank=True, null=True)),
                ('request_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarrantyRenewal',
            fields=[
                ('renewal_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('renewal_warranty_start', models.DateField(blank=True, null=True)),
                ('renewal_warranty_end', models.DateField(blank=True, null=True)),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'warranty_renewal',
                'managed': False,
            },
        ),
    ]
