# Generated by Django 5.1.6 on 2025-03-13 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='bom',
            name='type',
            field=models.CharField(default='Project', max_length=15),
        ),
    ]
