# Generated by Django 5.1.6 on 2025-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0002_bom_date_bom_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('bom_id', models.CharField(db_column='bom_id', max_length=255, primary_key=True, serialize=False)),
                ('quantity_of_product', models.IntegerField(db_column='quantity_of_product', null=True)),
                ('quantity_of_material', models.IntegerField(db_column='quantity_of_material', null=True)),
                ('product_description', models.TextField(blank=True, db_column='product_description', null=True)),
                ('specific_notes', models.TextField(blank=True, db_column='specific_notes', null=True)),
                ('cost_per_raw_material', models.DecimalField(db_column='cost_per_raw_material', decimal_places=2, max_digits=10)),
                ('total_cost_of_raw_materials', models.DecimalField(db_column='total_cost_of_raw_materials', decimal_places=2, max_digits=10)),
                ('cost_of_production', models.DecimalField(blank=True, db_column='cost_of_production', decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(blank=True, db_column='labor_cost', decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, db_column='total_cost', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'bill_of_materials',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
