# Generated by Django 5.1.6 on 2025-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0003_billofmaterials_delete_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProjectOrderPricing',
            fields=[
                ('non_project_costing_id', models.CharField(db_column='non_project_costing_id', max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity', null=True)),
                ('product_price', models.DecimalField(blank=True, db_column='product_price', decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, db_column='final_price', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'non_project_order_pricing',
                'managed': False,
            },
        ),
    ]
