# Generated by Django 5.1.6 on 2025-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0004_nonprojectorderpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('labor_cost_id', models.CharField(db_column='labor_cost_id', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'labor_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMats',
            fields=[
                ('product_mats_id', models.CharField(db_column='product_mats_id', max_length=255, primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(db_column='quantity_required', decimal_places=2, max_digits=10)),
                ('cost_of_used_materials', models.DecimalField(db_column='cost_of_used_materials', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_mats',
                'managed': False,
            },
        ),
    ]
