# Generated by Django 5.1.6 on 2025-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0005_laborcost_productmats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRawMaterialCost',
            fields=[
                ('product', models.CharField(db_column='product', max_length=255, primary_key=True, serialize=False)),
                ('quantity_of_product', models.IntegerField(db_column='quantity_of_product')),
                ('raw_material', models.CharField(db_column='raw_material', max_length=255)),
                ('quantity_of_raw_material', models.DecimalField(db_column='quantity_of_raw_material', decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure', default='unit')),
                ('cost_per_raw_material', models.DecimalField(db_column='cost_per_raw_material', decimal_places=2, max_digits=10)),
                ('total_cost_of_raw_materials', models.DecimalField(db_column='total_cost_of_raw_materials', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_raw_material_costs',
                'managed': False,
            },
        ),
    ]
