# Generated by Django 5.1.6 on 2025-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0006_productrawmaterialcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMList',
            fields=[
                ('bom_no', models.CharField(db_column='bom_id', max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='type')),
                ('status', models.TextField(db_column='status')),
                ('date_created', models.DateField(db_column='date_created')),
            ],
            options={
                'db_table': 'bom_list',
                'managed': False,
            },
        ),
    ]
