# Generated by Django 5.1.6 on 2025-04-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0007_bomlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('order_no', models.CharField(db_column='Order No.', max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='Type')),
                ('details', models.TextField(db_column='Details')),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'order_list',
                'managed': False,
            },
        ),
    ]
