# Generated by Django 5.1.6 on 2025-04-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0008_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('statement_id', models.CharField(db_column='Statement ID', max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='Product ID')),
                ('product_name', models.TextField(db_column='Product')),
                ('product_description', models.TextField(db_column='Product Description')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_pricing',
                'managed': False,
            },
        ),
    ]
