# Generated by Django 5.1.6 on 2025-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0009_productpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfRawMaterials',
            fields=[
                ('product_id', models.CharField(db_column='Product ID', max_length=255, primary_key=True, serialize=False)),
                ('raw_material', models.CharField(db_column='Raw Material')),
                ('material_id', models.CharField(db_column='Material ID')),
                ('rm_quantity', models.DecimalField(db_column='RM Quantity', decimal_places=2, max_digits=10)),
                ('units', models.CharField(db_column='Units')),
                ('unit_cost', models.DecimalField(db_column='Unit Cost', decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(db_column='Total Cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cost_of_materials',
                'managed': False,
            },
        ),
    ]
