# Generated by Django 5.1.6 on 2025-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0010_costofrawmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductionCosts',
            fields=[
                ('order_id', models.CharField(db_column='order_id', max_length=255, primary_key=True, serialize=False)),
                ('ext_project_request_id', models.CharField(db_column='ext_project_request_id')),
                ('project_id', models.CharField(db_column='project_id')),
                ('task_id', models.CharField(db_column='task_id')),
                ('production_order_id', models.CharField(db_column='production_order_id')),
                ('cost_of_production', models.DecimalField(db_column='cost_of_production', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order_production_costs',
                'managed': False,
            },
        ),
    ]
