# Generated by Django 5.1.6 on 2025-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0011_orderproductioncosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOrder',
            fields=[
                ('order_id', models.CharField(db_column='order_id', max_length=255, primary_key=True, serialize=False)),
                ('ext_project_request_id', models.CharField(db_column='ext_project_request_id')),
                ('project_id', models.CharField(db_column='project_id')),
                ('task_id', models.CharField(db_column='task_id')),
                ('production_order_id', models.CharField(db_column='production_order_id')),
                ('employee_id', models.CharField(db_column='employee_id')),
                ('days_worked', models.IntegerField(db_column='days_worked')),
                ('daily_rate', models.DecimalField(db_column='daily_rate', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'employee_order',
                'managed': False,
            },
        ),
    ]
