# Generated by Django 5.1.6 on 2025-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0012_employeeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProjectProductCost',
            fields=[
                ('statement_id', models.CharField(db_column='statement_id', max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='product_id')),
                ('product_name', models.TextField(db_column='product_name')),
                ('description', models.TextField(db_column='description')),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('product_cost', models.DecimalField(db_column='Product Cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'np_product_cost',
                'managed': False,
            },
        ),
    ]
