# Generated by Django 5.1.6 on 2025-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0013_nonprojectproductcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBOMDetail',
            fields=[
                ('statement_id', models.CharField(db_column='statement_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.TextField(db_column='Product')),
                ('qty_of_product', models.IntegerField(db_column='Qty. Of Product')),
                ('raw_material_name', models.TextField(db_column='Raw Material')),
                ('qty_of_raw_material', models.DecimalField(db_column='Qty. Of Raw Material', decimal_places=2, max_digits=10)),
                ('units', models.CharField(db_column='Units')),
                ('cost_per_rm', models.DecimalField(db_column='Cost Per Raw Material', decimal_places=2, max_digits=10)),
                ('total_cost_per_rm', models.DecimalField(db_column='Total Cost Per Raw Material', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'project_bom_detail',
                'managed': False,
            },
        ),
    ]
