# Generated by Django 5.1.6 on 2025-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0014_projectbomdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalItemOrderList',
            fields=[
                ('service_order_item_id', models.CharField(db_column='service_order_item_id', max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='type')),
                ('description', models.TextField(db_column='description_details')),
                ('date', models.DateField(db_column='date')),
            ],
            options={
                'db_table': 'principal_item_orders',
                'managed': False,
            },
        ),
    ]
