# Generated by Django 5.1.6 on 2025-04-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0015_principalitemorderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalOrderItem',
            fields=[
                ('service_order_item_id', models.CharField(db_column='service_order_item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(db_column='item_id')),
                ('material_id', models.CharField(db_column='material_id')),
                ('item_name', models.TextField(db_column='item_name')),
                ('item_quantity', models.IntegerField(db_column='item_quantity')),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure')),
                ('item_price', models.DecimalField(db_column='item_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'principal_item_details',
                'managed': False,
            },
        ),
    ]
