# Generated by Django 5.1.6 on 2025-04-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0016_principalorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalItems',
            fields=[
                ('principal_item_id', models.CharField(db_column='principal_item_id', max_length=255, primary_key=True, serialize=False)),
                ('mark_up_price', models.DecimalField(db_column='mark_up_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'principal_items',
                'managed': False,
            },
        ),
    ]
