# Generated by Django 5.1.6 on 2025-04-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0017_principalitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNpop',
            fields=[
                ('tracking_npop_id', models.CharField(db_column='tracking_npop_id', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status')),
            ],
            options={
                'db_table': 'tracking_npop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingPrincipal',
            fields=[
                ('tracking_principal_id', models.CharField(db_column='tracking_principal_id', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status')),
            ],
            options={
                'db_table': 'tracking_principal',
                'managed': False,
            },
        ),
    ]
