# Generated by Django 5.1.6 on 2025-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0018_trackingnpop_trackingprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProductMats',
            fields=[
                ('statement_id', models.CharField(db_column='statement_id', max_length=255, primary_key=True, serialize=False)),
                ('product_mats_id', models.CharField(db_column='product_mats_id')),
                ('quantity_required', models.DecimalField(db_column='quantity_required', decimal_places=2, max_digits=10)),
                ('cost_per_raw_material', models.DecimalField(db_column='cost_per_raw_material', decimal_places=2, max_digits=10)),
                ('total_cost_of_raw_materials', models.DecimalField(db_column='total_cost_of_raw_materials', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'project_productmats',
                'managed': False,
            },
        ),
    ]
