# Generated by Django 5.1.6 on 2025-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_of_material', '0019_projectproductmats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProjectBOMDetail',
            fields=[
                ('statement_id', models.CharField(db_column='statement_id', max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='product_id')),
                ('product_name', models.TextField(db_column='product_name')),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure')),
                ('selling_price', models.DecimalField(db_column='selling_price', decimal_places=2, max_digits=10)),
                ('product_cost', models.DecimalField(db_column='Product Cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'np_bom_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalBOMDetail',
            fields=[
                ('service_order_item_id', models.CharField(db_column='service_order_item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(db_column='item_id')),
                ('material_id', models.CharField(db_column='material_id')),
                ('item_name', models.TextField(db_column='item_name')),
                ('item_quantity', models.IntegerField(db_column='item_quantity')),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure')),
                ('item_price', models.DecimalField(db_column='item_price', decimal_places=2, max_digits=10)),
                ('total_item_price', models.DecimalField(db_column='total_item_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'principal_bom_detail',
                'managed': False,
            },
        ),
    ]
