# Generated by Django 5.1.6 on 2025-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name')),
                ('item_description', models.TextField(db_column='item_description')),
            ],
            options={
                'db_table': 'product_material',
                'managed': False,
            },
        ),
    ]
