# Generated by Django 5.1.6 on 2025-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRawMaterial',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name')),
                ('material_id', models.CharField(db_column='material_id')),
                ('quantity_required', models.DecimalField(db_column='quantity_required', decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure')),
            ],
            options={
                'db_table': 'product_rawmaterial',
                'managed': False,
            },
        ),
    ]
