# Generated by Django 5.1.6 on 2025-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_materials', '0002_productrawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectProduct',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name')),
                ('item_description', models.TextField(db_column='item_description')),
            ],
            options={
                'db_table': 'select_product',
                'managed': False,
            },
        ),
    ]
