# Generated by Django 5.1.6 on 2025-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_materials', '0003_selectproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMaterial',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name')),
                ('unit_of_measure', models.CharField(db_column='unit_of_measure')),
                ('item_price', models.DecimalField(db_column='item_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'select_material',
                'managed': False,
            },
        ),
    ]
